# Generated by Django 4.2.2 on 2023-06-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=128)),
                ('api_token', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya_id', models.IntegerField()),
                ('name', models.CharField(max_length=122)),
                ('display_name', models.CharField(blank=True, max_length=122, null=True)),
                ('zone', models.IntegerField()),
                ('is_deliverable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_id', models.IntegerField()),
                ('name', models.CharField(max_length=122)),
                ('display_name', models.CharField(blank=True, max_length=122, null=True)),
                ('is_deliverable', models.BooleanField()),
                ('has_stop_desk', models.BooleanField()),
                ('delivery_time_parcel', models.IntegerField()),
                ('delivery_time_payment', models.IntegerField(blank=True, null=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.wilaya')),
            ],
        ),
    ]
