# Generated by Django 4.2.2 on 2023-06-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_setting_sending_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='communes_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='parcel_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='wilaya_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
