# Generated by Django 4.2.2 on 2023-07-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_setting_communes_url_setting_parcel_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.IntegerField()),
                ('name', models.CharField(max_length=122)),
                ('display_name', models.CharField(blank=True, max_length=122, null=True)),
                ('address', models.CharField(blank=True, max_length=122, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.commune')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.wilaya')),
            ],
        ),
    ]
