# Generated by Django 4.2.2 on 2023-08-18 16:57

import customization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_alter_section_description_alter_section_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=customization.models.upload_section_image_path),
        ),
    ]
