# Generated by Django 4.2.2 on 2023-07-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_collection_order_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error',
            field=models.CharField(blank=True, choices=[('No Error', 'No Error'), ('HTTP Error', 'HTTP Error'), ('Time out', 'Time out'), ('Connection error', 'Exception request'), ('Exception request', 'Exception request'), ('KeyError', 'KeyError'), ('One occurrence', 'One occurrence'), ('Duplicated', 'Duplicated'), ('Failed', 'Failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
