# Generated by Django 4.2.2 on 2023-07-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_error_order_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.AddField(
            model_name='order',
            name='error_message',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
