# Generated by Django 4.2.2 on 2023-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_message_order_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='error',
            field=models.CharField(blank=True, choices=[('No Error', 'No Error'), ('No delivery settings', 'No delivery settings'), ('HTTP Error', 'HTTP Error'), ('Time out', 'Time out'), ('Connection error', 'Exception request'), ('Exception request', 'Exception request'), ('KeyError', 'KeyError'), ('One occurrence', 'One occurrence'), ('Duplicated', 'Duplicated'), ('Failed', 'Failed')], max_length=20, null=True),
        ),
    ]
