# Generated by Django 4.2.2 on 2023-07-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstatus_color_alter_order_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
