# Generated by Django 4.2.2 on 2023-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_created_on_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_stopdesk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
