# Generated by Django 4.2.2 on 2023-06-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_variant_color_remove_variant_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='address',
        ),
    ]
