# Generated by Django 4.2.2 on 2023-06-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_order_address_order_city_order_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
