# Generated by Django 4.2.2 on 2023-06-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_tracking_id_alter_order_city_alter_order_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
