# Generated by Django 4.2.2 on 2023-06-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_first_name_order_fulol_adress_order_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fulol_adress',
            new_name='full_adress',
        ),
    ]
