# Generated by Django 4.2.2 on 2023-06-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_fulol_adress_order_full_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
