# Generated by Django 4.2.2 on 2023-08-12 22:05

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_collection_image_path),
        ),
    ]
