# Generated by Django 4.2.2 on 2023-08-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_collection_is_featured_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
